### ISSUE TITLE
Not able to install latest version of ArchiveXL

### ISSUE THREAD

**Issue by hbjydev** [E1337Kat/cyberpunk2077_ext_redux#335]
**Describe the bug**
When I try to install ArchiveXL, it fails because of (what looks like) extra files existing.

**To Reproduce**
1. Go to the ArchiveXL Nexus page (https://www.nexusmods.com/cyberpunk2077/mods/4198?tab=files)
2. Click on Mod Manager Download
3. In Vortex, see the download go through and see it try to install

**Expected behavior**
I expected the mod to be correctly installed

**Screenshots**
![image](https://user-images.githubusercontent.com/22327045/209433790-3b54e3eb-b837-4b2b-bdb5-927f59318471.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Mod: ArchiveXL
 - Extension Version: 0.9.5 according to Vortex extensions tab

**Comment by azraal** [comment]
I really think there shouldn't be any reason why a mod manager would totally block the installation of a mod. Heavy warning are fine write it red if necessary. But a user should have the possibility to take responsibilities and force install.

Anyway, since I still want to keep a clean directory when I purge the mods by vortex here is a quick workaround to still install through vortex albeit with manual steps.
- Download and unpack the archiveXL mod from the nexus
- zip both directory separately and install manually both archives through vortex.

You can also fill the mods information from the nexus to keep track of the current version but you'll get warnings

**Comment by Tenzian** [comment]
>  But a user should have the possibility to take responsibilities and force install.

You can right-click and select `Install (as-is)`

**Comment by E1337Kat** [comment]
Ya, I want to rework it a bit, but haven't found time or ideas on what to do. Hopefully the fix can get put out sooner rather than later.

**Comment by azraal** [comment]
> > But a user should have the possibility to take responsibilities and force install.
> 
> You can right-click and select `Install (as-is)`

I didn't know this, thanks.

**Comment by mrtrizer** [comment]
> > But a user should have the possibility to take responsibilities and force install.
> 
> You can right-click and select `Install (as-is)`

Excuse me. Right-click where exactly? 😄
